require("nixCatsUtils.catPacker").setup({
  "folke/lazydev.nvim",
  { "BirdeeHub/lze", lazy = false },
  { "BirdeeHub/lzextras", lazy = false },
  "gbprod/substitute.nvim",
  "folke/flash.nvim",
  { "numToStr/Comment.nvim", name = "comment.nvim" },
  "antosha417/nvim-lsp-file-operations",
  "michaelb/sniprun",
  { "ahmedkhalf/project.nvim", lazy = false },
  { "stevearc/oil.nvim", lazy = false },
  "mikavilpas/yazi.nvim",
  "stevearc/aerial.nvim",
  "Pocco81/auto-save.nvim",
  { "nvim-lua/plenary.nvim", lazy = false },
  "antoinemadec/FixCursorHold.nvim",
  { "nvim-neotest/nvim-nio", lazy = false },
  "nvim-neotest/neotest",
  "nvim-neotest/neotest-plenary",
  "nvim-neotest/neotest-jest",
  "thenbe/neotest-playwright",
  "marilari88/neotest-vitest",
  "rcarriga/nvim-dap-ui",
  "theHamsta/nvim-dap-virtual-text",
  "mfussenegger/nvim-dap",
  "folke/trouble.nvim",
  "MunifTanjim/nui.nvim",
  { "nvim-tree/nvim-web-devicons", lazy = false },
  { "folke/snacks.nvim", lazy = false },
  "folke/which-key.nvim",
  "folke/todo-comments.nvim",
  "aznhe21/actions-preview.nvim",
  "nvim-lualine/lualine.nvim",
  "arkav/lualine-lsp-progress",
  "rachartier/tiny-inline-diagnostic.nvim",
  "folke/noice.nvim",
  { "loctvl842/monokai-pro.nvim", lazy = false },
  "smjonas/inc-rename.nvim",
  "MeanderingProgrammer/render-markdown.nvim",
  { "nvim-treesitter/nvim-treesitter-textobjects", name = "treesitter-textobjects", version = "main" },
  { "nvim-treesitter/nvim-treesitter", version = "main" },
  "williamboman/mason.nvim",
  "williamboman/mason-lspconfig.nvim",
  "neovim/nvim-lspconfig",
  "pmizio/typescript-tools.nvim",
  "vuki656/package-info.nvim",
  "jmbuhr/otter.nvim",
  { "b0o/schemastore.nvim", lazy = false },
  { "mrcjkb/rustaceanvim", lazy = false },
  { "L3MON4D3/LuaSnip", name = "luasnip" },
  { "saghen/blink.cmp", version = "v1" },
  "Saghen/blink.compat",
  "xzbdmw/colorful-menu.nvim",
  "kylechui/nvim-surround",
  "windwp/nvim-autopairs",
  "windwp/nvim-ts-autotag",
  "alexandre-abrioux/blink-cmp-npm.nvim",
  "mfussenegger/nvim-lint",
  "stevearc/conform.nvim",
  "esmuellert/nvim-eslint",
  "mbbill/undotree",
  "sindrets/diffview.nvim",
  "lewis6991/gitsigns.nvim",
  "nickjvandyke/opencode.nvim",
  "zbirenbaum/copilot.lua",
  "CopilotC-Nvim/CopilotChat.nvim",
  "fang2hou/blink-copilot",
})
