local gh = function(x) return 'https://github.com/' .. x end

require("nixCatsUtils.catPacker").setup({
  { src = gh("folke/lazydev.nvim") },
  gh("BirdeeHub/lze"),
  gh("BirdeeHub/lzextras"),
  { src = gh("gbprod/substitute.nvim") },
  { src = gh("folke/flash.nvim") },
  { src = gh("numToStr/Comment.nvim"), name = "comment.nvim" },
  { src = gh("antosha417/nvim-lsp-file-operations") },
  { src = gh("michaelb/sniprun") },
  gh("ahmedkhalf/project.nvim"),
  gh("stevearc/oil.nvim"),
  { src = gh("mikavilpas/yazi.nvim") },
  { src = gh("stevearc/aerial.nvim") },
  { src = gh("Pocco81/auto-save.nvim") },
  gh("nvim-lua/plenary.nvim"),
  { src = gh("antoinemadec/FixCursorHold.nvim") },
  gh("nvim-neotest/nvim-nio"),
  { src = gh("nvim-neotest/neotest") },
  { src = gh("nvim-neotest/neotest-plenary") },
  { src = gh("nvim-neotest/neotest-jest") },
  { src = gh("thenbe/neotest-playwright") },
  { src = gh("marilari88/neotest-vitest") },
  { src = gh("rcarriga/nvim-dap-ui") },
  { src = gh("theHamsta/nvim-dap-virtual-text") },
  { src = gh("mfussenegger/nvim-dap") },
  { src = gh("folke/trouble.nvim") },
  { src = gh("MunifTanjim/nui.nvim") },
  gh("nvim-tree/nvim-web-devicons"),
  gh("folke/snacks.nvim"),
  { src = gh("folke/which-key.nvim") },
  { src = gh("folke/todo-comments.nvim") },
  { src = gh("aznhe21/actions-preview.nvim") },
  { src = gh("nvim-lualine/lualine.nvim") },
  { src = gh("arkav/lualine-lsp-progress") },
  { src = gh("rachartier/tiny-inline-diagnostic.nvim") },
  { src = gh("folke/noice.nvim") },
  gh("loctvl842/monokai-pro.nvim"),
  { src = gh("smjonas/inc-rename.nvim") },
  { src = gh("MeanderingProgrammer/render-markdown.nvim") },
  { src = gh("nvim-treesitter/nvim-treesitter-textobjects"), name = "treesitter-textobjects", version = "main" },
  { src = gh("nvim-treesitter/nvim-treesitter"), version = "main" },
  { src = gh("williamboman/mason.nvim") },
  { src = gh("williamboman/mason-lspconfig.nvim") },
  { src = gh("neovim/nvim-lspconfig") },
  { src = gh("pmizio/typescript-tools.nvim") },
  { src = gh("vuki656/package-info.nvim") },
  { src = gh("jmbuhr/otter.nvim") },
  gh("b0o/schemastore.nvim"),
  gh("mrcjkb/rustaceanvim"),
  { src = gh("L3MON4D3/LuaSnip"), name = "luasnip" },
  { src = gh("saghen/blink.cmp"), version = "v1" },
  { src = gh("Saghen/blink.compat") },
  { src = gh("xzbdmw/colorful-menu.nvim") },
  { src = gh("kylechui/nvim-surround") },
  { src = gh("windwp/nvim-autopairs") },
  { src = gh("windwp/nvim-ts-autotag") },
  { src = gh("alexandre-abrioux/blink-cmp-npm.nvim") },
  { src = gh("mfussenegger/nvim-lint") },
  { src = gh("stevearc/conform.nvim") },
  { src = gh("esmuellert/nvim-eslint") },
  { src = gh("mbbill/undotree") },
  { src = gh("sindrets/diffview.nvim") },
  { src = gh("lewis6991/gitsigns.nvim") },
  { src = gh("nickjvandyke/opencode.nvim") },
  { src = gh("zbirenbaum/copilot.lua") },
  { src = gh("CopilotC-Nvim/CopilotChat.nvim") },
  { src = gh("fang2hou/blink-copilot") },
})
